name: sugarblood
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.11
  intl: ^0.20.2
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^7.0.1
  google_fonts: ^6.1.0
  intl_phone_field: ^3.2.0
  http: ^1.3.0
  file_picker: ^10.1.2
  fl_chart: ^0.71.0
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/diabetes_illustration.png
    - assets/doctor_team.png
    - assets/home.png
    - assets/people.png
    - assets/stethoscope.png
    - assets/compass.png
    - assets/plat_1.jpg
    - assets/plat_2.jpg
    - assets/plat_3.jpg
    - assets/plat_4.jpg
    - assets/plat_5.jpg
    - assets/Frame 26.png
    - assets/mineral-water 1.png
    - assets/clock 1.png
    - assets/sleep.png
    - assets/hydration.png
    - assets/medication.png
    - assets/activity.png
    - assets/food.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png" 
